import axios from "axios";
export const state = () => ({
  isActive: true,
  token:
    "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJST2tZdUJMRjNKTTJnbnl2TnA0bVotVTRsNDdhZ3FGaWxfN2tLMnRVYnhFIn0.eyJleHAiOjE2MzM3MjQwNDMsImlhdCI6MTYzMzY4ODA0MywianRpIjoiYzg5YTEwMDQtNjY1Zi00NzJmLWE3MzYtMWQ1NWNhNWVkNzE0IiwiaXNzIjoiaHR0cDovL215aW53aS5ibGFuYy50ZWNoOjgwOTEvYXV0aC9yZWFsbXMvaW53aWJvIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjRhMzQwNzQzLTU0Y2YtNGNmZi1hZmIwLWFjNzAwNWE4MDdjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImJvLWFwaS1jbGllbnQiLCJzZXNzaW9uX3N0YXRlIjoiMjhlYjA5OGUtYmI0OS00ZGE0LTlmYWQtYWU4NDUzOWMyODNiIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWlud2libyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiIyOGViMDk4ZS1iYjQ5LTRkYTQtOWZhZC1hZTg0NTM5YzI4M2IiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfYjAwMiJ9.b9NSsAqfPCyODJEX7jdQbh0uekXO76YyyYupwJVizOn_rLm5GGNzoBeTSHon7XpaqVIIe8DG7WSfrOexaNyFJPGO9Y7RIuBStZDkOQQ4CgagWN0JxoOJMfYwzTeebWuJzekJkNJNF-9GiIoZ29zRSnBYRzj8_oAP2btzRgpOiWvXwy9UXECOwPSmm7_IrZbUBIhwgwUIBjF3fGLOiKI8axd5GhnmqiqT4EIzpFAUIl3aqMJmU_T6ep7p-pElkWd6pJE0mlTTEY5Ppfud1ewtVQjvD6rllPkVdjIEkER6hzDSAeqN-c97Ol87iOox9AeLxI7vLJAkP1h2d0-aT2nilw",
  sdata:
    "ewogICAgImNoYW5uZWwiOiAibW9iaWxlIiwKICAgICJhcHBpY2F0aW9uX29yaWdpbiI6ICJteUlud2kiLAogICAgInV1aWQiOiAiMTYzMTYwODc1NyIsCiAgICAiaXNSb2FtaW5nIjogdHJ1ZSwKICAgICJsYW5ndWFnZSI6ICJmciIsCiAgICAiYXBwVmVyc2lvbiI6ICIxLjAuMCIsCiAgICAib3MiOiAiYW5kcm9pZCIsCiAgICAib3NWZXJzaW9uIjoiNSIKfQ",
});

export const mutations = {
  setIsActive(state_app, payload) {
    state_app.isActive = payload;
  },
};

export const getters = {};

export const actions = {
  updateLangue(_, data) {
    return axios.put("api/ms-backoffice/v1/app-language", data);
  },
};
